#!/bin/sh

echo Stage 1
echo =======
echo 
echo "    Package Installation"
echo 
sudo apt-get install libelf-dev libncurses-dev git lzop uboot-mkimage libelf-dev libncurses-dev checkinstall build-essential subversion-tools cvs genext2fs gawk bison flex libglib2.0-dev texi2html texinfo automake libtool curl gtk-doc-tools expat libtool automake autoconf qemu binfmt-support qemu-user lzma
echo Stage 2
echo =======
echo
echo "    Cloning upstream minifs mini distro-maker"
echo
git clone http://oomz.net/git/minifs.git minifs
echo Stage 3
echo =======
echo
echo "    Applying patches and fixes"
echo
echo "        This tree is prepatched. Yay."
echo
#for fix in fix/*
#do
#	echo Running $fix
#	sh $fix
#done
cd minifs
export MINIFS_BOARD=df3120
./minifs_build.sh
