#!/bin/bash

export ENV_NAME=DF3120
export MINIFS_BOARD=df3120
export PS1="\[\033[1;34m\]($ENV_NAME)\[\033[0m\] $PS1"

MINIFS_ROOT=`pwd`/DF3120/minifs
PATH=$MINIFS_ROOT/toolchain/arm-v4t-linux-uclibcgnueabi/bin:$PATH
cd $MINIFS_ROOT/..
